### PR TITLE
Allow eval for code-patching

### PR DESCRIPTION
**Pull request by RblSb**
But with such red warning in debug console 
image

### CODE REVIEW

**Comment by RobDangerous** [comment]
Eval-Lyn approves.
grafik

But will the scary red text then just show up for everyone?

**Comment by RblSb** [comment]
Yea. Do you want khamake flag instead?

**Comment by RobDangerous** [comment]
Yes, if there's no automatic way to avoid the shock-text we should use a flag.

**Comment by RblSb** [comment]
#248

**Pull request closed without merging**
