### PR TITLE
Add native target define

### PR DESCRIPTION
**Pull request by RblSb**

### CODE REVIEW

**Comment by RobDangerous** [comment]
I'm not sure this is what has been decided ~10 years ago, have to dig it up.

**Comment by RblSb** [comment]
In this case, we have a complete separation of platforms like `kha_android`, `kha_android_native`, `kha_android_hl` and a one `sys_android` for all. We can invert this approach about `kha_` /` sys_`, but I think this will cause more problems.

**Comment by RblSb** [comment]
But it will break [such code](https://github.com/search?q=%23if+kha_android&type=Code), because everyone checks `android_native` as `kha_android`. So this can be considered as breaking change. But `sys_android_native` (system android native) is meh...

**Comment by RobDangerous** [comment]
sys_ is deprecated and shouldn't be used anymore, I just keep it around for backwards compatibility.

**Comment by RblSb** [comment]
Hmm, I was thinking of using it as `#if (sys_android || sys_ios)` to distinguish mobile platforms, if you agree to create separation by target in `kha_*`. Then it will be possible to distinguish both the platform without `if (native || hl || etc)` check.

**Comment by RobDangerous** [comment]
As it is right now (kha_android || kha_ios) is already possible.

**Comment by RblSb** [comment]
Okay, I see android has separate `kha_android_java`/`kha_android_hl` and will have `kha_android_native` (I will fix this), and also has` kha_android` to summarize. But I don’t like that `html5_native` also has` kha_html5`, because you need to write `if (kha_html5 || kha_html5_debug)`. Can make an exception? :P

**Comment by RobDangerous** [comment]
Should be if (kha_html5 && js) and I think that's ok.

**Comment by RblSb** [comment]
Everyone writes `#if html5` and js code inside, even Kha repo... But I don’t think someone decides to use html5_native in Kha, so that's up to you.

**Comment by RobDangerous** [comment]
That will have to change when the html5_native targets starts making sense for Haxe but I don't mind, those problems are easy to catch.

**Comment by RobDangerous** [comment]
I like it. Thanks for the patience.

**Comment by RobDangerous** [comment]
Done. @RblSb is that correct or did I get lost, too?

**Comment by RblSb** [comment]
We actually fixed here line about "kha_android_native will be defined."
Also, will update wiki in coming days with new secret kha hints.

**Pull request merged**
