### PR TITLE
allow to pass a specific path to a template in project.kha

### PR DESCRIPTION
**Pull request by wighawag**
Hi,

I added a new option in project.kha to pass a html file as template.
It will be used instead of the default template.
To do that I changed the code in main.js to parse the project before passing to the Html5Exporter

The change also mean that the index.html file is regenerated at every call to khamake but I think it is an improvement since now user can define their own html page and get the change for the project setting. A further imporvement would be to pass the parsed project file to the template (maybe using a js templating library). But this might be overkill.

Hope you like it

Thanks

### CODE REVIEW

**Comment by ratalaika** [comment]
I recommend you to correct the tabs to adjust to original KhaMake tab

**Comment by wighawag** [comment]
Since the pull request on canvas resize was accepted  I amended the commit to add 1 template on top of the other one (fixedSize) to support full window canvas on the html target
I think this new template should be the default one as the fixed size canvas is not nice on its own, (a blank background). but to keep the current behaviour I left the fixedSize html template the default.

an extra param in project.kha has been added : html
it specify the template to be used and can be a path relative to project.kha file
It can also be either "fixedSize" the current default template or "fullWindow"

**Comment by RobDangerous** [comment]
I'm not so sure about this. Generally I see the included template as a thing for development only. It is already implemented such that you can just put your own html file in build/html5 and that won't be overridden. In the end html5 games often get integrated in some website and don't stand completely alone and the current template resembles that better I think.

**Comment by wighawag** [comment]
Do you mean that you do not like the whole pull request or just the idea of replacing the current default template with the new template as the default ?

For me the main reason to not use the current default template is that it is not usable on mobiles at all. Providing another template to deal with mobile seems a nice idea.

Regarding the current behaviour of khamake not overriding the index.html, while it allow developer to use another html file it does not allow the developer to use the template properties (like {{width}}) if needed. It is true though that for my use case (mobile full window canvas) it is sufficient.

To defend my pull request, the only thing it changes is that the index.html is overridden, In the same time it provide the developer the ability to pass its own template, providing the same benefit and more.

While you are right that in many case the actual html will be different as it need to be part of a greater website. the new template mechanism allow the developer to replicate such environment a bit better.

**Comment by RobDangerous** [comment]
Hmm, mobile. Didn't really consider mobile until Rafael and you started working on it. Have to think some more about what's the best strategy here (pull request will therefore likely be open until Thursday - sorry about that).

**Comment by wighawag** [comment]
no worries

**Comment by RobDangerous** [comment]
Uh oh, project.kha doesn't exist anymore. Sorry 😢

**Pull request closed without merging**
