### PR TITLE
Better commandline

### PR DESCRIPTION
**Pull request by hamaluik**
The current Khamake command line leaves much to be desired. For example, there's no way to list which targets you can compile for (the only help is): `-t --target (Target platform)`. There also isn't any checking to see if the command line is valid, so a user can easily run:

```bash
node Kha/make.js win32
```

And have khamake chug merrily along until it runs into a rather opaque error. Similarly, the `--help` flag lists all possible commands at all possible times, implying I could compile for HTML5 with raytracing, or use `metal` graphics on Windows.

This PR aims to alleviate these issues by more rigorously defining the command line and providing context-appropriate help and feedback to users.

An example output when running khamake now is:

```
$> node khamake.js
usage: khamake [-h] <command> ...

Build tool for Kha

Positional arguments:
  <command>
    init       Initialize a Kha project
    server     Run local http server for html5 target
    krom       build for the krom target
    windows    build for the Windows target
    windowsapp
               build for the WindowsApp target
    ps3        build for the PlayStation3 target
    ios        build for the iOS target
    osx        build for the OSX target
    android    build for the Android target
    xbox360    build for the Xbox360 target
    linux      build for the Linux target
    html5      build for the HTML5 target
    html5worker
               build for the HTML5Worker target
    flash      build for the Flash target
    wpf        build for the WPF target
    java       build for the Java target
    psm        build for the PlayStationMobile target
    tizen      build for the Tizen target
    unity      build for the Unity target
    node       build for the Node target
    debug-html5
               build for the DebugHTML5 target
    empty      build for the Empty target
    pi         build for the Pi target
    tvos       build for the tvOS target

Optional arguments:
  -h, --help   Show this help message and exit.

For detailed help about a specific command, use: khamake <command> -h
```

And for example, running the earlier example of `node Kha/make.js win32` gives:

```bash
$> node khamake.js win32
usage: khamake [-h] <command> ...
khamake: error: argument "<command>": Invalid choice: win32 (choose from [init, server, krom, windows, windowsapp, ps3, ios, osx, android, xbox360, linux, html5, html5worker, flash, wpf, java, psm, tizen, unity, node, debug-html5, empty, pi, tvos])
```

When attempting to compile for a specific target, you can see options relevant to that specific target. For example, compiling for Windows gives the help:

```
$> node khamake.js windows -h
usage: khamake windows [-h] [--from PATH] [--to PATH] [--projectfile FILENAME]
                       [--main CLASS] [-a {default,directsound,wasapi}]
                       [-k PATH] [--haxe PATH] [--nohaxe] [--ffmpeg PATH]
                       [--ogg COMMAND] [--mp3 COMMAND] [--aac COMMAND]
                       [--krafix PATH] [--noshaders] [--noproject]
                       [--onlydata] [--debug] [--silent] [-w] [--glsl2]
                       [--shaderversion VERSION]
                       [--parallel-asset-conversion PROCESSES] [--haxe3]
                       [-v {vs2010,vs2012,vs2013,vs2015,vs2017}]
                       [--vr {none,oculus}] [--raytrace {none,dxr}]
                       [-g {default,opengl,direct3d9,direct3d11,direct3d12,vulkan}]
                       [--compile] [--run]


build for the Windows target

Optional arguments:
  -h, --help            Show this help message and exit.
  --from PATH           Location of your project. The default value is ".".
  --to PATH             Build location. The default value is "build".
  --projectfile FILENAME
                        Name of your project file. The default value is
                        "khafile.js".
  --main CLASS          Entrypoint for the haxe code (-main argument),
                        defaults to "Main" The default value is "Main".
  -a {default,directsound,wasapi}, --audio {default,directsound,wasapi}
                        Audio api to use. The default value is "default".
  -k PATH, --kha PATH   Location of Kha directory. The default value is "".
  --haxe PATH           Location of Haxe directory. The default value is "".
  --nohaxe              Do not compile Haxe sources
  --ffmpeg PATH         Location of ffmpeg executable. The default value is
                        "".
  --ogg COMMAND         Commandline for running the ogg encoder. The default
                        value is "".
  --mp3 COMMAND         Commandline for running the mp3 encoder. The default
                        value is "".
  --aac COMMAND         Commandline for running the aac encoder. The default
                        value is "".
  --krafix PATH         Location of krafix shader compiler. The default value
                        is "".
  --noshaders           Do not compile shaders
  --noproject           Only source files. Don't generate project files
  --onlydata            Only assets/data. Don't generate project files
  --debug               Compile in debug mode
  --silent              Silent mode
  -w, --watch           Watch files and recompile on change
  --glsl2               Use experimental SPIRV-Cross glsl mode
  --shaderversion VERSION
                        Set target shader version manually
  --parallel-asset-conversion PROCESSES
                        Experimental - Spawn multiple processes during asset
                        and shader conversion. Possible values: 0: disabled
                        (default value) -1: choose number of processes
                        automatically N: specify number of processes manually.
                         The default value is 0.
  --haxe3               Use the battle tested Haxe 3 compiler instead of the
                        cutting edge not really released yet Haxe 4 compiler
  -v {vs2010,vs2012,vs2013,vs2015,vs2017}, --visualstudio {vs2010,vs2012,vs2013,vs2015,vs2017}
                        Version of Visual Studio to use. The default value is
                        "vs2017".
  --vr {none,oculus}    Target VR device. The default value is "none".
  --raytrace {none,dxr}
                        Target raytracing API. The default value is "none".
  -g {default,opengl,direct3d9,direct3d11,direct3d12,vulkan}, --graphics {default,opengl,direct3d9,direct3d11,direct3d12,vulkan}
                        Graphics api to use. The default value is "default".
  --compile             Compile executable
  --run                 Run executable
```

While the similar help page for compiling for HTML5 doesn't include selection for Visual Studio, ray tracing, graphics, compilation, and running because those options don't apply to the HTML5 target.

There are a few breaking changes brought about by this PR:

1. `--init` has been changed to a top-level action, so the command is now `node khamake.js init` rather than `node khamake.js --init`
2.  `--server` has been changed to a top-level action, so the command is now `node khamake.js server` rather than `node khamake.js --server`
3. There is no longer a default platform. Running `node khamake.js` without any commands will give the help page instead of automatically generating and compiling for your current native platform
4. Commands which used to be silently ignored now generate errors. For example, running `node khamake.js -g vulkan` will give an error indicating that you cannot set graphics on HTML5 (before, it would just run and generate as if you had never given the `-g vulkan` command, not communicating the issue at all with the user).

I'd be happy to make any changes you suggest, but given that I interact with khamake on the command line almost daily these quality of life improvements would be greatly appreciated by myself at least, and I feel they would make things easier for new users as well.

### CODE REVIEW

**Comment by RobDangerous** [comment]
Ooooh, that's nice and long overdue. I'll have a look at maybe reducing the new dependencies (like to keep those minimal), then I'll merge. Thanks a lot!

**Comment by sh-dave** [comment]
Wow nice, but something to keep in mind: `node Kha/make.js win32` can actually be valid if you defined a custom `win32` target in current khamake (but i'm not sure anyone uses this).

**Comment by sh-dave** [comment]
And is it possible to condense the duplicate options display for long and shorthand options, so say
` -g, --graphics {default,opengl,direct3d9,direct3d11,direct3d12,vulkan}` instead of
` -g {default,opengl,direct3d9,direct3d11,direct3d12,vulkan}, --graphics {default,opengl,direct3d9,direct3d11,direct3d12,vulkan}`?

**Comment by hamaluik** [comment]
Hmm, not immediately based on the command line parser I’m using, but I’ll look into it, it certainly is way more verbose than it needs to be / should be.

**Comment by RobDangerous** [comment]
Very sorry but I'm moving large portions of the build-system to C.

**Pull request closed without merging**
