### PR TITLE
Check if arg is target

### PR DESCRIPTION
**Pull request by RblSb**
Want to send additional arguments to khamake / my khafile, but they are detected as targets.

### CODE REVIEW

**Comment by sh-dave** [comment]
Isn't that better handled via custom targets, it seems less fragile to have everything in your khafile.js to me?

**Comment by RblSb** [comment]
I need to send path to private key file, don't think that custom target will help here. Maybe `--custom "stringdata"` is better option?

**Comment by sh-dave** [comment]
A `switch (platform) { case 'android': ... }` might be enough for that?

**Comment by RblSb** [comment]
Use case:
```js
const opts = getOpts();
someTargetOptions.pathToLicense = opts.licenseKey;

function getOpts() {
	const id = process.argv.indexOf("--opts");
	// default properties for khafile
	const s = id != -1 ? process.argv[id + 1] : `{
		"licenseKey": "none"
	}`;
	return JSON.parse(s);
}
```
And actual call:
```
node Kha/make android-native --opts '{"licenseKey": "verySecret"}'
```

**Comment by sh-dave** [comment]
Yes i get what you want to do, but why don't you just hardcode it in the khafile?

**Comment by RblSb** [comment]
Want to separate private stuff from main project if i upload it with git history someday.

**Comment by XANOZOID** [comment]
@RblSb have you tried something like this?

```.gitignore
#  . . . gitignore
privateConfig.json
```

config.json
```json
{
      "privateKey": "..."
}
```

```js
// khafile.js

let fs = require('fs');

let project = new Project('....');
let config = JSON.parse(fs.readFileSync('./config.json', 'utf8'));

// use your configs . . . 
```

I tried doing it a more javascripty way but that wasn't really working. But this works.

**Comment by RblSb** [comment]
Yep, that works. If we don't want custom args as alternative i can close this. Btw simplest way to implement this will be specifying target as always first argument to khamake. Probably nobody writes `node Kha/make -w html5`?

**Comment by XANOZOID** [comment]
I can only speak from experience but, based on a conversation I've observed, it does not sound like a feature Robert would want for Khamake. I could be wrong about how serious Robert was, or misunderstand what he meant, but it sounds like he is against the idea of command-line tools that we interface with to begin with. So adding a feature which is representative of writing it by hand is basically going against that idea. The ideal environment for Khamake is interfaced with a tool like VSCode or related. 

That being said, I would somewhat enjoy this feature for other reasons but, for the case of injecting configuration, not so much. I wouldn't mind a wrapper for my example above, though. 

I would still leave this up though if one of us can come up with a more compelling reason to utilize this.

**Comment by RobDangerous** [comment]
That doesn't sound like I was serious at all.

**Comment by sh-dave** [comment]
Maybe deprecate the positional argument and force the use of `--target`?

**Comment by RobDangerous** [comment]
No way, that's my favorite feature. Have to admit though, I don't even understand what's the problem here.

**Comment by RobDangerous** [comment]
Like, if you want more arguments, just add them to the options array in khamake.ts.

**Comment by RblSb** [comment]
I dont want custom args handling in khamake, i just want to handle them in khafile with my behaviour. But i see your answer already.

**Comment by RobDangerous** [comment]
Ah, now I understand. Let's add something ala --custom for that situation. Or --end and everything after that goes to the khafile only.

**Comment by sh-dave** [comment]
Use the posix double dashes `--` as delimiter? See guideline 10 at the bottom [here](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html).

**Comment by RobDangerous** [comment]
I knew I've seen something like that before. Yes, let's do it like that.

**Comment by RblSb** [comment]
`--custom "data"` or `-- "data" "data2"` (if i understand guideline)? Maybe `--` can be used for something more useful in future.`readFileSync` with gitignore seems fine too anyway, so I will not insist.

**Comment by sh-dave** [comment]
Everything after `--` isn't processed by khamake.

**Pull request closed without merging**
