### PR TITLE
Add smart_strings define

### PR DESCRIPTION
**Pull request by RblSb**
Fixes https://github.com/Kode/Kha/issues/1004

### CODE REVIEW

**Comment by RblSb** [comment]
I think we can revert it now? If we only target haxe rc3

**Comment by RobDangerous** [comment]
The --haxe3 option still exists and will exist until Haxe 4 proper is finally out.

**Comment by RobDangerous** [comment]
But we only use one version of hxcpp. Is smart strings now the default in there?

**Comment by RblSb** [comment]
But you do https://github.com/Kode/Kha/commit/e0b11f1081af91c91855e41394bd8f25547c5c90 without #if haxe4 check :)
Yes, should be default after (https://github.com/HaxeFoundation/haxe/pull/8089), i think?

**Comment by RobDangerous** [comment]
I only break Haxe3 accidentally, not on purpose. It's important for when I'm sued about it.
Not sure com.defines is actually used with Kha's build system, have to check.

**Pull request merged**
