### PR TITLE
Allow ogg as sound asset

### PR DESCRIPTION
**Pull request by RblSb**
Lets discuss what cases is broken?
Also this code adds ogg to sounds and blobs, we should separate it with some flag for compatibility?

### CODE REVIEW

**Comment by RobDangerous** [comment]
Sorry but I do not want to support oggs like that, it would prevent future optimizations (hardware audio decoding is a thing and it's usually not ogg-based). If at all, we would have to add an ogg decoder that can run during builds.

**Comment by RblSb** [comment]
I understand, but can we support ogg with ffmpeg flag then, for example?
Currently we throw error about video conversion without ffmpeg anyway, as i remember? So we can throw error for ogg resources too, if target wants something more that ogg for sounds, like mp4 in html5.

**Comment by RobDangerous** [comment]
Yes, we can do something similar for compressed audio formats. There already is unfinished support for flac like that (which by the way makes way more sense as a source audio format than ogg).

**Comment by RblSb** [comment]
In what way it is not finished?
Will try to detect ogg as sound only with ffmpeg. Need some flag for that? It will break ogg detection as blobs, but i think it is not critical, because there is no way to convert blob to sound.

**Comment by RobDangerous** [comment]
Blob to sound conversion is possible. Nonetheless it's ok and I don't think we need a flag.
And I think I was mistaken about flac support not being finished.

**Comment by RblSb** [comment]
Ok. Possible in Kha api way?

**Comment by RobDangerous** [comment]
Sure, use new kha.audio2.StreamChannel(blob.toBytes()) or call directly into kha.audio2.ogg, which would be the proper way to do it.

**Comment by RblSb** [comment]
Should be fine now? The only question is [this block](https://github.com/Kode/khamake/blob/master/src/Exporters/KoreExporter.ts#L96), which trigger error on non-wav sounds for Kore targets if `quality == 1.0`.

**Comment by RobDangerous** [comment]
Indeed, looks fine.

**Pull request merged**
