### PR TITLE
Update node_modules

### PR DESCRIPTION
**Pull request by RblSb**
Watch mode eats 0.0% cpu instead of 8% for me.
Latest `@types/node` has conflict with typescript, so i set fixed version.
Actual change:
```json
"dependencies": {
    "@types/fs-extra": "^5.1.0",
    "@types/node": "10.12.0",
    "chokidar": "^3.0.2",
    "fs-extra": "^6.0.1",
    "node-static": "^0.7.11",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "promise-parallel-throttle": "^3.3.0",
    "typescript": "^3.6.3"
  }
```

### CODE REVIEW

**Comment by RblSb** [comment]
I guess any commit update here is little bad for Kha repository size? Would be nice to remove node_modules from git, but then one command install will stop working...

**Comment by RblSb** [comment]
Ah, `/node_modules/typescript` is already in `.gitignore`, should be fine then.

**Comment by RobDangerous** [comment]
Sorry, but sending npm updates as pull requests doesn't make sense to me. Just tell me what needs updating and I'll take care of it.

**Comment by RblSb** [comment]
Okay, then updated dependency list in the description, check if this is fine for you.

**Pull request closed without merging**
