### PR TITLE
Fix kha_debug_html5

### PR DESCRIPTION
**Pull request by RblSb**

### CODE REVIEW

**Comment by RblSb** [comment]
@RobDangerous hxml html5-native defines come from koremake emscripten target or from another place? Hard to find.

**Comment by RobDangerous** [comment]
Here it is: https://github.com/Kode/khamake/blob/master/src/Exporters/KoreExporter.ts#L38
But please don't add the kha_html5 define in this case, the native target is a totally different thing.

**Comment by RblSb** [comment]
@RobDangerous yeah, for this reason we need to remove this line from there in case of html5-native target (at the moment it is added without postfix). I think the only way to fix this is to do `if (this.options.target! = 'html5') ...`?

**Comment by RblSb** [comment]
Or check for `this.sysdir() === 'html5-native'`;

**Comment by RobDangerous** [comment]
What is "this line" and what is "there"?

**Comment by RblSb** [comment]
Your link above, `defines.push('kha_' + this.options.target);` will be `defines.push('kha_html5')` for html5-native target, so its wrong

**Comment by RobDangerous** [comment]
Aha. Same for android-native. I think we had a long discussion about that like years ago. Have to look it up.

**Pull request merged**
